import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const href =
  "https://app.binance.com/?_dp=L21wL2FwcD9hcHBJZD14b3FYeFVTTVJjY0xDclpOUmVibXpqJnN0YXJ0UGFnZVBhdGg9TDNCaFoyVnpMMlJoYzJoaWIyRnlaQzF1WlhjdmFXNWtaWGc9JnN0YXJ0UGFnZVF1ZXJ5PWQyTTlkMk1sTTBFMFpqWXhOVGt6TWkwMFlXSTJMVFE0TXpZdFlqUmtaaTFqT1RSbE5tVmlZV015TkdRbE5EQXhKVE5HWW5KcFpHZGxKVE5FZDNOekpUTkJKVEpHSlRKR2JtSnpkSEpsWVcwdWVXbHVaM2RoYm1kMFpXTm9MbTVsZENVeVJuZGhiR3hsZEMxamIyNXVaV04wYjNJbE1qWnJaWGtsTTBRNE9Ea3lNR1poWkRsbE5XTTVOVGhtTURnMVlqTTNabVZrTkdKbFltUTNPREE0WWpBelpEa3haREZoTkRFMk9EaGpZalF3WmpZd1ltTmpaVEE1TnpReEpUSTJjMk5sYm1VbE0wUmlhV1FtYVhORVpXVndUR2x1YXoxMGNuVmxKbWxrUFRFMk9ETXdNRFV5T1RneU1UQQ";

export default function Home() {
  const clickWithDelay = async () => {
    await new Promise((resolve) => setTimeout(resolve, 1500));
    const a = document.createElement("a");
    a.href = href;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };
  const click = () => {
    const a = document.createElement("a");
    a.href = href;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <button onClick={clickWithDelay}>open deep link with delay 1s</button>
          <button onClick={click}>open deep link without delay</button>
        </div>
      </main>
    </>
  );
}
